### ISSUE TITLE
Cut a v3.0.0 release?

### ISSUE THREAD

**Issue by ari-becker** [arianvp/dhall-kubernetes#108]
As we (my employer) prefer to pin to tagged releases and not just GitHub commit hashes, I'd like to cut a `v3.0.0` release with the following release notes:

```text
Additions:
* Generate Dhall schemas for multiple Kubernetes versions
* Support `CustomResourceDefinition` in the generator
* `nix-shell` support for `dhall-kubernetes-generator`
* Improve test coverage for `scripts/generate.sh`
* Generator automatically excludes older Kubernetes object versions
* Add `--skipDuplicates` CLI flag and handler to the generator
* Add prefixMap option for specifying external import roots
Cleanup:
* Update omit-empty command in Readme
* Remove top-level `swagger2.json`
* Minimize unnecessary rebuilds
```

I have the permissions to do it myself, but I'm opening this as an issue in case somebody had some work that they'd like included in a `v3.0.0` release and they'd like to hold the release until then, or if somebody has feedback on the language above (maybe I misunderstood something?). So I'll wait 24 hours and then cut the release if there are no objections.

**Comment by Gabriella439** [comment]
Yeah, I think this is a good point to cut a new release, especially given that the last release was over a month ago.  I usually try to flush releases on a monthly basis

**Comment by ari-becker** [comment]
Release cut: https://github.com/dhall-lang/dhall-kubernetes/releases/tag/v3.0.0
