### ISSUE TITLE
Proposing a hardcoded exception: prefer autoscaler/v2beta2 over autoscaler/v1

### ISSUE THREAD

**Issue by ari-becker** [arianvp/dhall-kubernetes#112]
We're currently looking at building in `HorizontalPodAutoscaler`s into our deployments and I noticed that the `schema` exports `autoscaler/v1` rather than `autoscaler/v2beta2`, in line with the general desire to prefer exporting stable versions before beta versions.

I propose that, in the specific case of the `autoscaler` API, that a hard-coded exception be placed for `autoscaler` such that `autoscaler/v2beta2` is exported instead of `autoscaler/v1`. 

* The `autoscaler/v2beta2` effectively is stable - introduced in Kubernetes 1.12 and persisting as the latest version in current Kubernetes 1.17. 
* It is necessary to use the `v2beta2` API to scale based on custom metrics (for us, Kafka topic lag) rather than only being able to set CPU thresholds for autoscaling.
* Last I checked, no additional work was planned on the `HorizontalPodAutoscaler` API since efforts were being put instead into a multi-dimensional autoscaler (i.e. something that eclipses both the vertical pod autoscaler and the horizontal pod autoscaler, since they don't currently play nice with each other).

In the interim I'm going to work around this issue by importing the relevant `v2beta2` schemas directly, rather than using them directly from the package.

**Comment by Gabriella439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-kubernetes/pull/113

**Comment by ari-becker** [comment]
@Gabriel439 looks fantastic, thank you!

**Comment by Gabriella439** [comment]
@ari-becker: You're welcome! 🙂
