### ISSUE TITLE
Request for a v4.0.0 release for the Optionals

### ISSUE THREAD

**Issue by TristanCacqueray** [arianvp/dhall-kubernetes#114]
Hi, would it be possible to cut a new release to include the latest change adding Optional types, in particular for the `emptyDir` and `flocker` volume attribute.

**Comment by Gabriella439** [comment]
I just cut a new release: https://github.com/dhall-lang/dhall-kubernetes/releases/tag/v4.0.0

**Comment by TristanCacqueray** [comment]
@Gabriel439 oh thanks, that is great!

**Comment by Gabriella439** [comment]
@TristanCacqueray: You're welcome! 🙂
