### ISSUE TITLE
CustomResourceDefinition generator producing empty files

### ISSUE THREAD

**Issue by javierarrieta** [arianvp/dhall-kubernetes#116]
Hi,

I was trying to use the `dhall-kubernetes-generator` for a couple of CRD's that we use a lot in our company but they are generated empty schema/type files

I don't get any error, so it is a bit difficult for me to debug, the CRD's I have tested are 

https://raw.githubusercontent.com/zalando-incubator/kubernetes-on-aws/dev/cluster/manifests/01-platformcredentialsset/customresourcedefinition.yaml

https://raw.githubusercontent.com/zalando-incubator/stackset-controller/v1.1.29/docs/stackset_crd.yaml

Any help greatly appreciated as some of them a really big definitions

**Comment by Gabriella439** [comment]
@javierarrieta: I have a pull request up to improve the error messages:

https://github.com/dhall-lang/dhall-kubernetes/pull/117

When I tested on your two CRD files, I got:

```bash
$ dhall-kubernetes-generator --crd example0.yaml
dhall-kubernetes-generator: user error (The CustomResourceDefinitionSpec is missing the validation field)

$ dhall-kubernetes-generator --crd example1.yaml
dhall-kubernetes-generator: user error (The CustomResourceValidation is missing the openApiv3Schema field)
```

I didn't write that code, so I don't know if those fields should really be required or not, and I can fix the logic if necessary.

**Comment by javierarrieta** [comment]
Hi @Gabriel439 thanks for checking. I know, @amarrella and @retnuh did. That PR looks good, would help debugging issues with the CRD

**Comment by Gabriella439** [comment]
Alright, then I'll mark this as fixed by https://github.com/dhall-lang/dhall-kubernetes/pull/117.  Feel free to reopen if the CRD support is too restrictive, which I can still fix
