### ISSUE TITLE
Issue in generating defs for 1.18

### ISSUE THREAD

**Issue by AS011** [arianvp/dhall-kubernetes#128]
when I run /scripts/generate.sh i get an error 

/```
build/dhall-1.33.0/src/Dhall/Tutorial.hs:374: failure in expression `input auto "https://raw.githubusercontent.com/dhall-lang/dhall-haskell/18e4e9a18dc53271146df3ccf5b4177c3552236b/examples/True" :: IO Bool'
expected: True
 but got: *** Exception:
          ^
          \ESC[1;31mError\ESC[0m: Remote host not found
          URL: https://raw.githubusercontent.com/dhall-lang/dhall-haskell/18e4e9a18dc53271146df3ccf5b4177c3552236b/examples/True
Examples: 241  Tried: 235  Errors: 0  Failures: 1
Test suite doctest: FAIL
Test suite logged to: dist/test/dhall-1.33.0-doctest.log
0 of 2 test suites (0 of 2 test cases) passed.
builder for '/nix/store/zmy7xvqga0sbwvnmbv11yc19kr7bcbfd-dhall-1.33.0.drv' failed with exit code 1
building '/nix/store/pix5bsrhh2djraady9r3pcbp8lkjm09c-dhall-1.33.0.drv'...
cannot build derivation '/nix/store/kmak6v2chbagr405ydxvbb9wc1k7m7v9-dhall-json-1.7.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/wjzmyrilngxmn5pq7nkdaph8k4j20pha-dhall-kubernetes-generator-0.1.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/nwrmw59ld2hds594683df0mm2mzwiph1-dhall-kubernetes-aggregate.drv', '/nix/store/wjzmyrilngxmn5pq7nkdaph8k4j20pha-dhall-kubernetes-generator-0.1.0.0.drv' failed
```

**Comment by Gabriella439** [comment]
@AS011: Could you try again on this branch: https://github.com/dhall-lang/dhall-kubernetes/pull/130

I think that might fix the build failure you are running into
