### ISSUE TITLE
How to generate types for 1.18

### ISSUE THREAD

**Issue by AS011** [arianvp/dhall-kubernetes#131]
I want to generate types for Kubernetes 1.18 as they are for 1.17 
Like in the image below we have types as 
![image](https://user-images.githubusercontent.com/26535491/88141277-e6168500-cc10-11ea-937c-9c19f78cdaad.png)

I want to generate the same for 1.18 I followed the same procedure mentioned in the readme i.e.
`./scripts/add-kubernetes-release.sh 1.18`
`echo 1.18 > ./nix/preferred.txt`
`./scripts/generate.sh `

But I couldn't find any 1.18 folder with types all I was getting an error in the terminal as - 

![image](https://user-images.githubusercontent.com/26535491/88141532-6c32cb80-cc11-11ea-99e4-c6e36646bd31.png)

**Comment by Gabriella439** [comment]
@AS011: It might have been a brief interruption in network connectivity.  I ran the same steps myself and got further, failing with a different error:

```
Freezing ./defaults.dhall
Checking ./defaults.dhall
Freezing ./types.dhall
Checking ./types.dhall
Freezing ./schemas.dhall
Checking ./schemas.dhall
Freezing ./typesUnion.dhall
Checking ./typesUnion.dhall
Freezing ./package.dhall
Checking ./package.dhall
Freezing ./examples/aws-iam-authenticator-chart.dhall
Checking ./examples/aws-iam-authenticator-chart.dhall
Freezing ./examples/deployment.dhall
Checking ./examples/deployment.dhall
Freezing ./examples/deploymentSimple.dhall
Checking ./examples/deploymentSimple.dhall
Freezing ./examples/ingress.dhall
Checking ./examples/ingress.dhall

Use "dhall --explain" for detailed errors

Error: Expression doesn't match annotation

  …
→ { http : …
           { paths : …
                     { - pathType : …
                     ,   backend : { - resource : …
                                   ,   serviceName : - Optional …
                                                     + Text
                                   ,   servicePort : - Optional …
                                                     + < … : … > (a union type)
                                   }
                     , …
                     }
           }
  , …
  }

22│       λ(service : Service) →
23│         { host = Some service.host
24│         , http = Some
25│           { paths =
26│             [ { backend =
27│                 { serviceName = service.name
28│                 , servicePort = kubernetes.IntOrString.Int 80
29│                 }
30│               , path = None Text
31│               }
32│             ]
33│           }
34│         }
35│

/nix/store/0nx66pd3c7ijplv95sf0kkvw12dg7m1s-package-dhall-kubernetes-1.18/examples/ingress.dhall:22:7
builder for '/nix/store/r2x3vrl8zm6kksjxcma97ig3k6753d7p-package-dhall-kubernetes-1.18.drv' failed with exit code 1
error: build of '/nix/store/r2x3vrl8zm6kksjxcma97ig3k6753d7p-package-dhall-kubernetes-1.18.drv' failed
```

However, I put up a pull request to fix that by only building the examples and README for the preferred version (which I kept at 1.17 for now until the examples are update for 1.18).  That pull request also adds 1.18 support:

https://github.com/dhall-lang/dhall-kubernetes/pull/132

**Comment by AS011** [comment]
@Gabriel439  Thanks for your help. One more thing I need help with supposing I want to generate Kubernetes YAML file with apiVersion: monitoring.coreos.com/v1  kind: ServiceMonitor so what types we can use as far as I know there is no tyoe defined as ServiceMontior there is only Service type in Dhall.

**Comment by Gabriella439** [comment]
@AS011: Yeah, this repository only generates definitions based on whatever is available in https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json.  However, the `dhall-kubernetes-generator` executable that generates this repository also supports a custom `--crd` mode where you can supply a CRD file to generate additional definitions matching the same format as this repository.
