### ISSUE TITLE
Generate dhall files from  openapi's swagger.json

### ISSUE THREAD

**Issue by mikefaille** [arianvp/dhall-kubernetes#134]
I want to generate my own Dhall objects for Kubernetes from my current cluster. It will include my crd objects.

It possible to retrieve a `swagger.json` content from this kube-apiserver url
```
/openapi/v2
```

Thank you to consider this !

**Comment by Gabriella439** [comment]
@mikefaille: I might be misunderstanding the question, but you don't need a running server to obtain the OpenAPI (Swagger) specification file.  The specification file is available from the `kubernetes` repository here:

https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json

**Comment by TristanCacqueray** [comment]
@Gabriel439 It seems like the `swagger.json` provided by the running `/openapi/v2` endpoint contains extra resources (CRDs) available in the cluster. Thus I think @mikefaille wants to run the dhall-kubernetes-generator manually.

**Comment by mikefaille** [comment]
@TristanCacqueray yes !

**Comment by Gabriella439** [comment]
Oh, in that case, if you know the address and port of your `kube-apiserver` then you can open it in your browser or download it using `curl`.  For example, on my local machine this works:

```
$ curl http://localhost:8080/openapi/v2
```

... because I have `kubernetes` running locally with `--insecure-port=8080` and `--bind-address=0.0.0.0`

**Comment by mikefaille** [comment]
`kubectl proxy` should do the job. After, how can I generate dhall assets for kubernetes that way ?

**Comment by mikefaille** [comment]
Oh, I see, the JSON from openapi is an argument for the generator !

**Comment by Gabriella439** [comment]
@mikefaille: Yeah, that's correct.  The `dhall-kubernetes-generator` takes an input OpenAPI spec and generates a directory tree similar to the one found in this repository.
