### ISSUE TITLE
A `Natural` might not be suited for `defaultMode`

### ISSUE THREAD

**Issue by damdo** [arianvp/dhall-kubernetes#139]
I'm using `defaultMode` in a `ConfigMapVolumeSource` here: https://github.com/dhall-lang/dhall-kubernetes/blob/c0586bcce543c4a96ee98d37bca2e35e25f17dc3/1.16/defaults/io.k8s.api.core.v1.ConfigMapVolumeSource.dhall#L1

And to do that I'm following the Kubernetes API reference here: https://v1-16.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#configmapvolumesource-v1-core

The reference states that `defaultMode` is an `integer` and that values should be between `0` and `0777`(note the leading zero):

Field | Description
-- | --
`defaultMode` `integer` | Optional: mode bits to use on created files by default. Must be a value between 0 and 0777. Defaults to 0644. Directories within the path are not affected by this setting. This might be in conflict with other options that affect the file mode, like fsGroup, and the result can be other mode bits set.

I've tried using `ConfigMapVolumeSource` with a `Natural` on `defaultMode` as allowed by the type definition.
```
 k8s.Volume::{
   , name = "my-name"
   , configMap = Some
       k8s.ConfigMapVolumeSource::{
         , name = Some "my-other-name"
         , defaultMode = Some 755
         }
   }
```
But the rendered YAML is not accepted by the (statefulset-)controller, which complains with:
```
Warning  FailedCreate  16s 
statefulset-controller  create Pod redis-sentinel-0 in StatefulSet redis-sentinel failed error: Pod "my-pod" is invalid:
[spec.volumes[1].configMap.defaultMode: Invalid value: 755: must be a number between 0 and 0777 (octal), both inclusive,
spec.volumes[2].configMap.defaultMode: Invalid value: 755: must be a number between 0 and 0777 (octal), both inclusive,
spec.volumes[3].configMap.defaultMode: Invalid value: 755: must be a number between 0 and 0777 (octal), both inclusive
```

This makes me think that `Natural`s might not be suitable for this as they don't embed leading zeros. We would need something more similar to an Octal or use a `Text` for this.

Or am I missing something? Thank you.

**Comment by sjakobi** [comment]
`755` in octal notation is `493` decimal. Does `defaultMode = Some 493` work?

Related: https://github.com/dhall-lang/dhall-haskell/issues/1988

**Comment by damdo** [comment]
Yes, that works, thank you very much!

I guess I can close this issue and we can rely on the one you linked for potential enhancements.
Thanks again.
