### ISSUE TITLE
Add `ManagedCertificate` type?

### ISSUE THREAD

**Issue by silky** [arianvp/dhall-kubernetes#143]
i'm not sure the protocol on what to include or not, but it would be convenient for me to have this one available - https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs

**Comment by Gabriella439** [comment]
@silky: We generate the types from the Kubernetes OpenAPI specification.  However, we also support generating additional types from a custom resource definition (CRD) file.

**Comment by silky** [comment]
nice, thanks :)

for other people, i think this is the place to look - https://github.com/dhall-lang/dhall-kubernetes/pull/98

maybe it's worth nothing that i guess while this will work well for generating new individual types, it won't help me emit my list of configs as a union of types (if i refer to the general dhall-kubernetes one).

but that's probably okay.

**Comment by Gabriella439** [comment]
@silky: Yeah, one thing the language is missing is an operator that is like `⩓` but for union types (e.g. `⩔`), because then you could extend the `typesUnion` type with your own types if such an operator existed.
