### ISSUE TITLE
Make `examples` folder

### ISSUE THREAD

**Issue by f-f** [arianvp/dhall-kubernetes#15]
The current state of things wrt usage examples is that there's only two "interactive" examples in the README.

I'd like to have an `examples` folder, to serve multiple purposes:
- Use it as a place to stash all the usage examples
- Use it to eventually run some tests in CI. E.g. we could test that executing some example always generates the same yaml.

**Comment by geigerzaehler** [comment]
I’ll take this if nobody minds.

**Comment by f-f** [comment]
Great, thanks!

After this and #18, I'd like to keep in the README only two examples:
- one example of the "high level" API, e.g. with `Deployment`
- one example of the low-level API, e.g. we can keep the current `Ingress` one

**Comment by geigerzaehler** [comment]
What do you think about this, @f-f:
* Move the examples in the README into the `examples` folder. 
* Create a script that verifies the YAML output against what is checked into source
* Create a script that inlines the example files into the readme. We check the processed readme into source and verify that is it up to date in CI.

**Comment by f-f** [comment]
@geigerzaehler sounds great 👍

**Comment by f-f** [comment]
Fixed in #27
