### ISSUE TITLE
Fix `Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+ ...`

### ISSUE THREAD

**Issue by igrep** [arianvp/dhall-kubernetes#166]
When deploying an Ingress, I always get the warning message.
My dhall-kubernetes is imported as:

```dhall
let k8s =
https://github.com/dhall-lang/dhall-kubernetes/raw/master/1.19/package.dhall sha256:2131ebbb78dce55fbe2383fa5f5f99278375fa34377b141c6e642db544280b55
```

**Comment by Gabriella439** [comment]
@igrep: Can you clarify what you believe should be fixed?  That warning does not come from Dhall

**Comment by igrep** [comment]
Oh, yes, the warning itself is by k8s. I guess the root cause is the default value of the `apiVersion` of `Ingress`.

https://github.com/dhall-lang/dhall-kubernetes/blob/3f1d8cc224644091cda2e5faa64a15081818bdd2/1.19/defaults/io.k8s.api.networking.v1beta1.Ingress.dhall#L1

So I think we should modify the default into `networking.k8s.io/v1` (and some other schema changes if necessary).
I could avoid by explicitly setting `apiVersion` by my dhall files, but it would be cumbersome.

**Comment by Gabriella439** [comment]
@igrep: `networking.k8s.io/v1` is the default for 1.19 on `master`, though.  See:

https://github.com/dhall-lang/dhall-kubernetes/blob/2ed2ffd073de6569014779284b61e4f5824de987/1.19/defaults.dhall#L629-L630

I think what might be happening is that the integrity check on your import might be incorrect so you're pulling in a stale/different import.  The hash I got was:

```
$ dhall hash <<< 'https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/master/1.19/package.dhall'
sha256:6774616f7d9dd3b3fc6ebde2f2efcafabb4a1bf1a68c0671571850c1d138861f
```

**Comment by igrep** [comment]
Oh, sorry, I referred to a wrong file. Thanks!

**Comment by Gabriella439** [comment]
You're welcome! 🙂
