### ISSUE TITLE
Higher-level API for user

### ISSUE THREAD

**Issue by geigerzaehler** [arianvp/dhall-kubernetes#18]
Using the API is still very verbose. As a user I mostly care about a couple of top-level resources from the APIs and their `spec` field. I think it would be great if this repo would provide a higher-level API built on the generated one that makes it easier to use. For example

```haskell
let Deployment = ./k8s/api/apps/v1/Deployment
in let metadata = Deployment.defaultMetadata { name = "hello-world" }
in let spec = Deployment.defaultSpec
  { selector = Deployment.defaultSelector { ... }
  , template = Deployment.defaultTemplate
    { metadata = Deployment.defaultMetadata
    , spec = Deployment.defaultPodSpec { ... } : Deployment.PodSpec
    }
  } 
in let deployment = Deployment.default { metadata = metadata, spec = spec }: Deployment.Type
```

In this example we actually make `spec` required because having a deployment without it is meaning less. This also reduces some boilerplate with the `Some` constructor.

You can also get all the default constructors and types from the `Deployment` record.

**Comment by f-f** [comment]
Very nice, +1 on all of this

**Comment by f-f** [comment]
@geigerzaehler question: should the "high-level" API dhall files be generated somehow (e.g. traversing the model and getting all the "descendant" models) or should they be hand-written?

**Comment by geigerzaehler** [comment]
That is something I’m experimenting with. To get something usable quickly and to get an idea of what the interface should look like I’m handcrafting this for a few resources (Deployment, Service, StatefulSet). If we see a good way to automate parts of it we should definitely do it. But I still expect some manual fine-tuning. I’ll try to submit something in the next days.

**Comment by f-f** [comment]
@geigerzaehler I started putting something together for this, and noticed that we won't be able to put in the same record types and values, because of https://github.com/dhall-lang/dhall-lang/pull/120

**Comment by f-f** [comment]
Update: I'm pushing my work for this issue in [this branch](https://github.com/dhall-lang/dhall-kubernetes/tree/feature/high-level-api)
