### ISSUE TITLE
How to find sha?

### ISSUE THREAD

**Issue by CThuleHansen** [arianvp/dhall-kubernetes#181]
When I try and import this as described in the readme I get:
```
 ./jnlp.dhall
  ↳ https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/master/package.dhall
  sha256:6bd75ef5494072c018014642c0cf3d7cbc6fbe6ec9ea3be8ef5a4e34430ca109

Error: Import integrity check failed

Expected hash:

↳ 6bd75ef5494072c018014642c0cf3d7cbc6fbe6ec9ea3be8ef5a4e34430ca109

Actual hash:

↳ e58b91c89c16e68a1989e961151fcaf2ea380de0cd21e7c044d05e88358ea159


2│       https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/master/package.dhall sha256:6bd75ef5494072c018014642c0cf3d7cbc6fbe6ec9ea3be8ef5a4e34430ca109

```

Is there a place in this repository where I can see the actually sha?
Or how do I compute it manually?

**Comment by Gabriella439** [comment]
@CThuleHansen: The actual SHA is the second one in the error message: `e58b91c89c16e68a1989e961151fcaf2ea380de0cd21e7c044d05e88358ea159`

However, if you ever want to compute it manually you can also use the `dhall hash` command, too:

```
$ dhall hash <<< 'https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/master/package.dhall'
```

**Comment by CThuleHansen** [comment]
Hehe sorry for an imprecise question, the error message was clear enough 🙂 the last part was what I needed. Thank you

**Comment by Gabriella439** [comment]
You're welcome! 🙂
