### ISSUE TITLE
Wrong release version?

### ISSUE THREAD

**Issue by JSGoodbodyWork** [arianvp/dhall-kubernetes#184]
The [6.0.0 release](https://github.com/dhall-lang/dhall-kubernetes/releases/tag/v6.0.0) says it supports `1.20` & `1.21`. However the package seems to be pointing to `1.17`:
https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/v6.0.0/package.dhall

As an example `IngressServiceBackend` should be available in `6.0.0` but it is not:
```
Error: Missing record field: IngressServiceBackend
```

**Comment by arianvp** [comment]
Correct. I made a PR. You can still import `https://github.com/dhall-lang/dhall-kubernetes/tree/master/1.22` directly as workaround

**Comment by Gabriella439** [comment]
What the release notes mean is that there are now `./1.21/` and `./1.22/` subdirectories.  The default selected version has not changed

However, we can change the default to whatever users prefer

**Comment by Gabriella439** [comment]
I have a PR up to upgrade to default Kubernetes version to 1.22: https://github.com/dhall-lang/dhall-kubernetes/pull/186
