### ISSUE TITLE
Release v7.0.0?

### ISSUE THREAD

**Issue by K0Te** [arianvp/dhall-kubernetes#188]
Hi @Gabriella439 ,

I've recently updated K8s clusters to 1.25 and now can no longer use the `v6.0.0` release, as it doesn't contain the definitions for 1.25.
Could you please create a new release `v7.0.0`?
Referring to https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/master/1.25/package.dhall makes me uneasy, as new commits might break the code :)
Thank you!

**Comment by rmk135** [comment]
If that's possible, I would ask to also make a release for supporting k8s 1.26.

**Comment by Gabriella439** [comment]
[v7.0.0](https://github.com/dhall-lang/dhall-kubernetes/releases/tag/v7.0.0) is out now, which includes support for Kubernetes 1.26
