### ISSUE TITLE
Invalid generated files

### ISSUE THREAD

**Issue by geigerzaehler** [arianvp/dhall-kubernetes#19]
Some generated files contain invalid Dhall code. This is due to properties named `$ref`. Dhall [does not support](https://github.com/dhall-lang/dhall-lang/blob/db36699432f39f77999e17c9d9adec438a39954d/standard/dhall.abnf#L125-L131) properties with `$` in the label.

I’d suggest we skip generation of these files to prevent users from using them. I don’t think it would be a good idea to sanitize the labels to something like `_dollar_ref` or similar since you would not be able to send the output to Kubernetes.

This is the list of invalid files:
```
./default/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec.dhall
./default/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceValidation.dhall
./default/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps.dhall
./default/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinition.dhall
./default/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionList.dhall
./default/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray.dhall
./default/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrBool.dhall
./default/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrStringArray.dhall
```

**Comment by f-f** [comment]
Nice, I was opening this same issue.

The problematic labels so far (e.g. see [here](https://github.com/dhall-lang/dhall-kubernetes/blob/master/default/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps.dhall)) are:
- `$ref`
- `$schema`

I propose we replace the `$` with `_`, so we'd get `_ref` and `_schema`. We should of course properly document this as well.

EDIT: oh sorry, I missed the part about sending the output to Kubernetes, you're right.
I wonder if we could add an escape hatch into `dhall-to-yaml` to automagically convert record keys from e.g. `_dollar_ref` to `$ref` when outputting (cc @Gabriel439)

**Comment by geigerzaehler** [comment]
> I wonder if we could add an escape hatch into dhall-to-yaml to automagically convert record keys from e.g. _dollar_ref to $ref when outputting (cc @Gabriel439)

Ideally Dhall would support more characters in labels. The ABNF file [mentions](https://github.com/dhall-lang/dhall-lang/blob/db36699432f39f77999e17c9d9adec438a39954d/standard/dhall.abnf#L129-L130) that this is not supported to “minimize the potential for code obfuscation”.

**Comment by Gabriella439** [comment]
I'd be totally fine adding more punctuation to quoted labels.  The comment about minimizing obfuscation is only referring to allowing other scripts (like Cyrillic) that can be used to generate different identifiers that look the same.

**Comment by f-f** [comment]
> I'd be totally fine adding more punctuation to quoted labels

Great. I'd propose then that we allow `$` as the first character of a label. (if this sounds good, I can put together a PR for `dhall-lang`)

**Comment by Gabriella439** [comment]
You can allow it as any character of a quoted label if you want

**Comment by f-f** [comment]
> You can allow it as any character of a quoted label if you want

Oh sorry, I missed the fact that you were referring to quoted labels. Makes sense to add new punctuation to quoted labels only 👍 

Opened https://github.com/dhall-lang/dhall-lang/pull/184

**Comment by f-f** [comment]
Once the change is merged in the standard, it will need to propagate to `dhall-haskell`, and this bug will be fixed with a new version of it.
In the meanwhile we could already fix the issue here, by emitting quoted labels if they contain a `$` (and we can merge that right away, because the generated files are broken anyways)
