### ISSUE TITLE
Pin Kube version?

### ISSUE THREAD

**Issue by f-f** [arianvp/dhall-kubernetes#4]
Currently we get the swagger spec from the `master` branch of Kubernetes.

Now, Kube should not remove any specifications, but they do deprecate some. On our end everything should be fine, as we never remove any types/default, we only add them.

Should we pin the Kube version? If yes, should we support multiple versions?

**Comment by arianvp** [comment]
Let's make it configurable. And release the generated files every time kube has a news release? People can then generate for older versions themselves if they want to.

**Comment by f-f** [comment]
Good idea.

I think the proper way to do this would be:
- make `convert.py` take a version as argument, if no argument provided use master
- Bonus: have a bot generate the things for us so we don't have to make these huge "refresh" commits
- Bonus: keep several branches (one for every "maintained" version of Kube), and tag releases in there

However, I personally don't mind if we always keep Kube's master committed here, we can probably leave it as is, and see if this is a problem going forward.

**Comment by f-f** [comment]
Update: since #24 we pin the Kube version, so we don't just pull the definitions from master anymore

**Comment by arianvp** [comment]
As Kubernetes source code is in Nix store,  we could, instead of making `convert.py` download
itself, just use whatever kube version is in `nixpkgs`.  This makes release management easier,
as we just have to bump `nixpkgs` to get new version:

```nix
# dhall-kubernetes.nix
{ stdenv, kubernetes, python3 }:
stdenv.mkDerivation rec {
  name = "dhall-kubernetes-${version}";
  version = kubernetes.version;
  src = kubernetes.src;
  buildPhase = ''
  python3 ${./convert.py} $src/api/openapi-spec/swagger.json
  '';
  installPhase = ''
  install out $out
  '';
}
```

```nix
# release.nix
let 
pkgs = pinnedpkgs;
in {  dhall-kubernetes =  pkgs.callPackage (import ./dhall-kubernetes.nix) {}; };
```

**Comment by f-f** [comment]
@arianvp that would be good by me, but I'll note that in this way we tie all the development to `nix` (that is, you could run `convert.py` only with `nix`).  
OTOH, assuming you already fetched that version of `nixpkgs`, in this way you could generate the new files offline (which is not possible ATM)
