### ISSUE TITLE
Cannot build with Nix sandboxing

### ISSUE THREAD

**Issue by arianvp** [arianvp/dhall-kubernetes#41]
Using 
```
nix-build release.nix -A dhall-kubernetes --arg src '{rev = "";}'
```

Fails because `dhall-1.18` fails to build. `dhall-1.18` test suite makes HTTP requests, which is verboten in Nix, causing the test suite to fail

**Comment by arianvp** [comment]
After `dontCheck`'ing the `dhall` package a next build failure occurs:


```
installing
Installing library in /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/lib/ghc-8.4.3/x86_64-linux-ghc-8.4.3/dhall-json-1.2.4-8fjbXiQihiiIyfHmnHKTlh
Installing executable dhall-to-json in /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/bin
Warning: The directory
/nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/bin is not in the
system search path.
Installing executable dhall-to-yaml in /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/bin
Warning: The directory
/nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/bin is not in the
system search path.
Registering library for dhall-json-1.2.4..
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4
shrinking /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/lib/ghc-8.4.3/x86_64-linux-ghc-8.4.3/dhall-json-1.2.4-8fjbXiQihiiIyfHmnHKTlh/HSdhall-json-1.2.4-8fjbXiQihiiIyfHmnHKTlh.o
wrong ELF type
shrinking /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/lib/ghc-8.4.3/x86_64-linux-ghc-8.4.3/libHSdhall-json-1.2.4-8fjbXiQihiiIyfHmnHKTlh-ghc8.4.3.so
shrinking /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/bin/dhall-to-json
shrinking /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/bin/dhall-to-yaml
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/lib  /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4/bin
patching script interpreter paths in /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4
checking for references to /build in /nix/store/dprp68qdll1k5c0qnrw8iaq658snszym-dhall-json-1.2.4...
wrong ELF type
building '/nix/store/3yar1d5qqzbsccrbmsd90dsr94hr8gnn-build-readme.drv'...
building '/nix/store/w3fmz1dbykj6f0nzlf08yrj04fc4s7lv-generated-files-compile.drv'...
building '/nix/store/iiw9rsj140yqbl1jbbyzgmamqxk7hgvs-validate-examples.drv'...
/build/.attr-0: ./scripts/build-readme.sh: /usr/bin/env: bad interpreter: No such file or directory
/build/.attr-0: ./scripts/check-source.py: /usr/bin/env: bad interpreter: No such file or directory
builder for '/nix/store/3yar1d5qqzbsccrbmsd90dsr94hr8gnn-build-readme.drv' failed with exit code 126
cannot build derivation '/nix/store/jby8i4rfs49mnk8ihnvwbmws3j4ppgvs-dhall-kubernetes.drv': 1 dependencies couldn't be built
error: build of '/nix/store/jby8i4rfs49mnk8ihnvwbmws3j4ppgvs-dhall-kubernetes.drv' failed

```

Does CI still even run?  I'm not sure how this wasn't caught :'D

**Comment by arianvp** [comment]
Ah wait, this is our own scripts that are broken :)     it can't find `python3`

**Comment by f-f** [comment]
@arianvp though it runs correctly on my machine 🤔  (I know, with nix this is not supposed to happen 😄)

What version of nix are you using? Are you on NixOS?

**Comment by arianvp** [comment]
NixOS

Do you have nix sandboxing enabled? Otherwise nix-build can have impurities.

(It's enabled by default on NixOS)

**Comment by f-f** [comment]
Right, build fails as well on my NixOS machine. Looks like we have some impurities in the nix files :) (Hydra works, but it doesn't use a sandbox, so I guess that's why build succeeds there)

**Comment by f-f** [comment]
Update on this: I got a bit further with making this more pure, and the current problem is that we also do network requests (to fetch the `Prelude`) in our scripts. The fix for this is to make the Prelude configurable [as it's done in `dhall-nethack`](https://github.com/dhall-lang/dhall-nethack/blob/master/Prelude.dhall), so we can depend from the prelude in nixpkgs. I'll put up a PR later today for this

**Comment by f-f** [comment]
@arianvp after #51 we can now use a local copy of the Prelude, by setting the `DHALL_PRELUDE` env var to a local import, so we can pull it from nixpkgs.
I think the only thing left for this issue is pulling the Kubernetes spec from nixpkgs as well?

**Comment by arianvp** [comment]
Yep! sounds about right.

Doesn't even have to be from `nixpkgs`. We could also directly do:

```
let swagger = lib.fetchurl { src = "https://raw.githubusercontent.com/kubernetes/kubernetes/${tag}/api/openapi-spec/swagger.json"; sha256 ="hash-of-the-file-here"}
```

and then in our derivation, assuming we support providing the output directory and the swagger input by command-line arguments,
```
buildPhase =  "./convert.py ${swagger} --out-dir $out"
```

**Comment by arianvp** [comment]
I'm working on a PR. gimme a moment :)

**Comment by arianvp** [comment]
@f-f  Building `dhall` on nixos seems to currently fail because `dhalls` own tests refer to the `Prelude` through http, which makes it impossible to run `dhall-1.21`'s doctests.

So I still can't build, eventhough we fixed our own stuff :)

This is probably also why `dhall-1.21` isn't in NixOS yet..


I disabled the tests for now for `dhall` to work around it but this might be not-ideal.   Though that's an upstream issue I guess

```
Test suite doctest: RUNNING...
/build/dhall-1.21.0/src/Dhall/Tutorial.hs:441: failure in expression `input auto "https://raw.githubusercontent.com/dhall-lang/dhall-haskell/18e4e9a18dc53271146df3ccf5b4177c3552236b/examples/True" :: IO Bool'
expected: "True"
 but got: "*** Exception: "
          "\8627 https://raw.githubusercontent.com/dhall-lang/dhall-haskell/18e4e9a18dc53271146df3ccf5b4177c3552236b/examples/True"
          ""
          "\ESC[1;31mError\ESC[0m: Remote host not found"
          ""
          ""
          "https://raw.githubusercontent.com/dhall-lang/dhall-haskell/18e4e9a18dc53271146df3ccf5b4177c3552236b/examples/True"
          "(input):1:1"

```
