### ISSUE TITLE
Add project references section to the docs?

### ISSUE THREAD

**Issue by ari-becker** [arianvp/dhall-kubernetes#50]
I just open-sourced [dhall-prometheus-operator](https://github.com/coralogix/dhall-prometheus-operator) - I was wondering if there could be a section in the README or the Wiki that links to open-source code which uses `dhall-kubernetes`.

Thanks!

**Comment by f-f** [comment]
Hi @ari-becker! Yes, that would be wonderful! Feel free to PR to the README adding such section 🙂 (otherwise I'll get to it in some days)
