### ISSUE TITLE
Port to Haskell?

### ISSUE THREAD

**Issue by arianvp** [arianvp/dhall-kubernetes#7]
This allows us to use the Reference implementation AST, to make sure we never generated invalid Dhall.

**Comment by f-f** [comment]
I was considering this idea as well, +1.
But I'd wait for that until the implementation has stabilized (e.g. after I deploy this to production) as hacking away on python it's much faster (for me at least).

**Comment by f-f** [comment]
Cool, I think at this point the Python implementation is reasonably stable (i.e. works for 99% of the objects), so we can proceed with this

**Comment by Gabriella439** [comment]
By the way, if you ever want to add this to the `dhall-haskell` "mega-project" feel free to do so.  The main reason I mention this is if you want the option to block the Haskell implementation from making breaking API changes until `dhall-kubernetes` has been fixed.  Of course, you don't have to do so if you don't want to

**Comment by f-f** [comment]
Thank you! 🙂

**Comment by f-f** [comment]
@arianvp work in progress (with horrible code) in this branch: https://github.com/dhall-lang/dhall-kubernetes/tree/haskell-implementation

**Comment by arianvp** [comment]
Cool. I'll be happy to review it or help coding. 

I think while we're at it we should remove the URL fetching code and just read swagger from stdin or from a file. This will also make it possible to run tests etc with nix sandbox enabled or for people to easily provide their own kube spec

**Comment by f-f** [comment]
@arianvp agreed! I'll keep the fetching code until I get feature-parity with the current script.
My plan is to get there + implement #46 (which is the main motivation for the rewrite), then I'll put up a PR so we can review/split work. I'll need your help at least with all the Nix things :)
