### ISSUE TITLE
Maybe revert back to using optionals even for emtpy records and lists

### ISSUE THREAD

**Issue by jvanbruegge** [arianvp/dhall-kubernetes#70]
In the current master, `Container` is broken, which is arguably one of the most central pieces of kubernetes. The reason is that `readinessProbe` (and also `livenessProbe`) are required in the `Container` type (see [here](https://github.com/dhall-lang/dhall-kubernetes/blob/master/types/io.k8s.api.core.v1.Container.dhall#L15)), but Kubernetes only allows this key to either miss completely or have at least one of the Probe keys defined.

Because of this and also the reason that the generated yaml is very noisy with a lot of `{}` and `[]`, I propose to go back to using `Optional` even for Lists and Records that contain only optionals.

**Comment by jvanbruegge** [comment]
I tried to hack on this myself, but I cannot install nix because I use Archlinux which does not play nicely and my clumsy attempts to create a docker container for the nix stuff is also not working because the generate script is failing

**Comment by jvanbruegge** [comment]
I also can't work around this with `grep` because the `livenessProbe` is sorted to the top, so grepping removes the dash needed to make a list of containers

**Comment by f-f** [comment]
@jvanbruegge would it work to use `--omitNull` instead of `--omitEmpty` as a workaround?

EDIT: oh it looks like you tried since you mentioned the lots of empty `{}` and `[]`

**Comment by jvanbruegge** [comment]
And again I am too stupid to read the documentation. I only used `--omitNull` because that was the way to do it earlier, I did not know about `--omitEmpty`

**Comment by jvanbruegge** [comment]
But one thing still stands. The current setup is not great for contributing

**Comment by f-f** [comment]
@jvanbruegge would you have any suggestions on how to make it more approachable?

**Comment by jvanbruegge** [comment]
I think the easiest, without changing all the infrastructure would be a docker container + documentation. I was able to run the updatePackages script successful, but generate errores with "is no tree object". At that point I gave up

**Comment by f-f** [comment]
@jvanbruegge I just encountered the same problem actually, and I'm a bit puzzled as well (it's not supposed to happen I think), @arianvp any ideas?

**Comment by f-f** [comment]
@jvanbruegge update: I fixed that error and I'm updating to the latest version of Kubernetes, I'll put up a PR later

**Comment by f-f** [comment]
@jvanbruegge: Nix problems should be fixed in #72
