### ISSUE TITLE
Dhall 10 first class modules

### ISSUE THREAD

**Issue by amarrella** [arianvp/dhall-kubernetes#79]
Hey there :)

What do you think about supporting first class modules now that dhall 10 supports them?
It could go from simply having a `package.dhall` with
```dhall
{ types = ./types.dhall,
  defaults = ./defaults.dhall,
  typesUnion = ./typesUnion.dhall
}
```
or something more complex (but maybe easier to discover?) like for each value we can have 
```dhall
-- package.dhall
{
  Deployment = ./Deployment/package.dhall
}

-- Deployment.dhall
{
    Type = ./Type.dhall,
     default = ./default.dhall
}
```

What do you think? 

Thanks again for this project!

**Comment by f-f** [comment]
Hi @amarrella! I'd say it would be pretty straightforward to have a simple `package.dhall` as you described. I guess also the second option would be fine, but it would require creating lots of folders (one for every object), which I'm less keen on

**Comment by amarrella** [comment]
Hey @f-f , thanks for the answer :) Either is fine I think, but I think the second option would mimic more the pattern that's in Prelude making discovery possibly easier.

Also the creation of lots of folders, each containing also a simple record with 
```dhall
{
  Type = ./Type.dhall,
  default = ./default.dhall
}
```
 will actually allow people to import a-la-carte what they want without having to import the whole library or having to write two lines for type and default. I think this way it will look more like a proper module system. We adopted this pattern in my company ([example](https://github.com/EarnestResearch/dhall-packages/tree/master/kubernetes/argocd)) and it feels more natural, also plays nice with dhall-lsp-server's autocomplete. 

But in the end up to you, a simple package.dhall like the first proposal would also work well :) 

Thanks again! :)

**Comment by arianvp** [comment]
At some point I think I proposed to go the nested directories approach, the code generator even supported it at some point, but then we ended up not doing it.  I can't remember the exact reasons  However I'm not too hung up on this.  I think having a nested directory structure which each a `package.dhall` in it makes sense.

and ooeh there is a `dhall-lsp-server`? TIL!

**Comment by amarrella** [comment]
@arianvp: since [this](https://github.com/dhall-lang/dhall-lang/issues/382) is about to be standardized I feel like the proposed directory structure maybe will be less important (or maybe will help with the implementation of the proposal - not sure yet) but I guess it depends on how that will be implemented

**Comment by Gabriella439** [comment]
Yeah, if I successfully standardize `T::r` syntax as discussed in https://github.com/dhall-lang/dhall-lang/issues/382#issuecomment-536334437 then it makes more sense to "transpose" the current `dhall-kubernetes` structure by having a top-level `package.dhall` with one field per resource type and each resource type has sub-fields of `Type` and `default{s}` (depending on what field names we decide on when standardizing it)

**Comment by Gabriella439** [comment]
Closing, as I believe every suggestion mentioned in this issue has been implemented
