### ISSUE TITLE
Prefer beta over alpha apis 

### ISSUE THREAD

**Issue by amarrella** [arianvp/dhall-kubernetes#81]
Hi there :)

I just encountered an issue today with Kubernetes 1.14 because the CronJob in `defaults.dhall` has as api version `batch/v2alpha1` instead of `batch/v1beta1`. 

I was able to solve it by overriding locally but I wonder if the default behavior should be preferring stable over beta over alpha in the defaults file. 

I didn't see any logic in the generator around that so I assume this was due to alphabetic ordering overriding? (both v2alpha 1 and v1beta1 exist).

Let me know what you think :) I can contribute it as a change if you think it's useful!

Thanks again for this awesome project 👍 and apologies for all the issues I open, if you have a better communication channel for this stuff let me know :)

**Comment by f-f** [comment]
@amarrella sorry for delay on this one, vacations and things happened 🙂 

Contributions are welcome of course! The models present in the `default` and so on are handpicked (there's a [giant list here](https://github.com/dhall-lang/dhall-kubernetes/blob/master/dhall-kubernetes-generator/src/Dhall/Kubernetes/Data.hs)), and the list is slightly opinionated - the policy so far is to prefer newer APIs (even if alpha) over older ones

I don't have a strong opinion on this (as long as the "tree of object versions" stays consistent inside the `defaults`, e.g. you don't want a `v2/alpha1` Deployment requiring a `v2/alpha` Metadata while including a `v1/beta2` Metadata in the defaults), so maybe others can chime in with their preference too

**Comment by amarrella** [comment]
@f-f sorry, I never replied to this. I see that there is a PR up to fix the specific case 👍

**Comment by Gabriella439** [comment]
This was fixed by #101
