### ISSUE TITLE
defaults.dhall does not contain the correct ingress path

### ISSUE THREAD

**Issue by oded-dd** [arianvp/dhall-kubernetes#82]
We are using `defaults.dhall` in order for imports.

When using Ingress we encountered the following typo:
Under `defaults.dhall` the path is setup as ```Ingress = ./defaults/io.k8s.api.networking.v1beta1.Ingress.dhall sha256:6d13f39daff533b29f92acb75fd7c405aaf6bd76056c508a833d745e71e0d414```

while the correct path sits under io.k8s.api.extensions.v1beta1.Ingress.dhall : ```https://github.com/dhall-lang/dhall-kubernetes/blob/master/defaults/io.k8s.api.extensions.v1beta1.Ingress.dhall```

**Comment by oded-dd** [comment]
Latest kubernetes versions support it. Sorry for missing it.

**Comment by f-f** [comment]
@oded-dd no worries at all 🙂
