### ISSUE TITLE
Go back to --omitNull instead of --omitEmpty

### ISSUE THREAD

**Issue by Gabriella439** [arianvp/dhall-kubernetes#86]
... which would imply wrapping all of the non-required fields in `Optional`.

I'll admit that I originally proposed `--omitEmpty` as part of #46 but in retrospect I think it may have been a mistake, for a few reasons:

One example is the issue described in https://github.com/dhall-lang/dhall-kubernetes/issues/78 caused by using `--omitEmpty`.  There @ari-becker quoted this from the documentation:

> A label selector is a label query over a set of resources. … An empty label selector matches all objects. A null label selector matches no objects.

... but when you use `omitEmpty` there is no way to distinguish a present but empty field (which means to match everything) from an absent field (which means to match nothing).  They are semantically distinct!

Similarly, #77 was caused by the same problem: accidentally omitting a field that was a record where transitive fields were all empty (the default `EmptyDirVolumeSource`), and that was semantically not the same thing.

Also, more generally, Kubernetes is not the only configuration format that has issues like these.  For example, I ran into a similar issue when working on encoding the Mergify configuration format in Dhall as part of [this chapter](https://github.com/Gabriel439/dhall-manual/blob/54715ffe5858116dd59c8f4727f292279a4442df/manuscript/01-YamlToDhall.md) of the `dhall-manual`.  It has a `delete_head_branch` field that stores a value of type `{}` and with `--omitEmpty` there is no way to preserve that field.

The reason I'm bringing up non-Kubernetes examples is because I'm trying to slowly come up with best practices as part of writing the Dhall manual and it's becoming increasingly clear to me that `--omitEmpty` is an anti-pattern that leads to issues like these because it runs the risk of throwing away semantically significant information.

You also don't gain much these days since all that `--omitEmpty` buys you is omitting a few `Some`s.  Now that we have the `::` operator (which has higher precedence than `Some`) it's actually not that bad to just keep all the `Some`s for non-required fields.  Also if the `Some`s were to really become problematic we could always revisit that in this issue:

* [Optional record fields again](https://github.com/dhall-lang/dhall-lang/issues/778)

**Comment by arianvp** [comment]
I am convinced

**Comment by amarrella** [comment]
Now that dhall's default behaviour is to to omit nulls I think we should also reflect it here going back to using `Optional (List _))` with a default of `None` instead of having `List _` with a default of `[]`.

This will help cover all the use cases. I have been bitten by this issue in https://github.com/EarnestResearch/dhall-packages/pull/49 (but i can't remove the --omit-empty flag until dhall-kubernetes does) and we resorted to using a dummy value, but it's not optimal

**Comment by Gabriella439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-kubernetes/pull/110
