### ISSUE TITLE
IntOrString missing from schemas.dhall

### ISSUE THREAD

**Issue by ari-becker** [arianvp/dhall-kubernetes#94]
Since the idea behind the `schemas.dhall` is to import the entire `dhall-kubernetes` package with one import, the `IntOrString` type should be added to `schemas.dhall` so that it can be referenced as:

```dhall
let Kubernetes = https://raw.githubusercontent.com/dhall-lang/dhall-kubernetes/v2.1.0/schemas.dhall
in Kubernetes.IntOrString.String "example"
```

As things stand, my imports file needs to reference the `IntOrString` separately, which isn't as simple/easy.

Found as I was trying to port code using the old `types.dhall` which was able to reference `Kubernetes.IntOrString`.

**Comment by Gabriella439** [comment]
@ari-becker: Could you create a pull request to add it?  I just add you as a contributor

Also, my main comment is that we should probably create a separate top-level `package.dhall`, which can re-export both `schemas` and `IntOrString`

**Comment by ari-becker** [comment]
@Gabriel439 thanks... truth be told, my Haskell skills still aren't up to snuff, and to be honest, I don't really see having time to work on this. But it is a fantastic issue for me to try and get my feet wet, at least since the amount of code is relatively small.

Which is to say, if I do end up submitting a PR for this, it'll probably be because nobody else found the time to tackle it first.

**Comment by Gabriella439** [comment]
@ari-becker: You shouldn't need Haskell to do this if I understand correctly.  This would just be authoring a `package.dhall` file that re-exports `schemas.dhall` and `IntOrString`

**Comment by ari-becker** [comment]
@Gabriel439 ah, I had an underlying assumption of the possibility of there being other exported unions in `types.dhall` which should also be added to a `package.dhall`, and as such any union in `types.dhall` should be added into a `package.dhall` dynamically as part of the generator. Even if today, `IntOrString` is the only union in `types.dhall`, I understand that there is a desire to introduce additional additional unions once the OpenAPI spec catches up and exposes various de-facto unions in the API that are currently exposed as `Optional` fields.

If a hand-written `package.dhall` (re-exporting `schemas.dhall` plus `IntOrString`) is acceptable, then a PR for that is trivial.

**Comment by Gabriella439** [comment]
@ari-becker: Yeah, a hand-written `package.dhall` is fine
